// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqs39GU6vJuestK-pxBmv3Rpz3AGzKo1M',
    appId: '1:193397693458:web:4fc1e38e51aaecf6bd8ccb',
    messagingSenderId: '193397693458',
    projectId: 'supermarket244-c0de3',
    authDomain: 'supermarket244-c0de3.firebaseapp.com',
    storageBucket: 'supermarket244-c0de3.firebasestorage.app',
    measurementId: 'G-7ZW1BBGC7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUzlbDoAYMJq_dcYAGKR-DyBhBsT-oL6Q',
    appId: '1:193397693458:android:2b19866abfe37b91bd8ccb',
    messagingSenderId: '193397693458',
    projectId: 'supermarket244-c0de3',
    storageBucket: 'supermarket244-c0de3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtUU1m5wmOUcJiftr9NEqQpZHfPXws8Ms',
    appId: '1:193397693458:ios:7dff46d460154886bd8ccb',
    messagingSenderId: '193397693458',
    projectId: 'supermarket244-c0de3',
    storageBucket: 'supermarket244-c0de3.firebasestorage.app',
    iosBundleId: 'com.example.localmartpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtUU1m5wmOUcJiftr9NEqQpZHfPXws8Ms',
    appId: '1:193397693458:ios:7dff46d460154886bd8ccb',
    messagingSenderId: '193397693458',
    projectId: 'supermarket244-c0de3',
    storageBucket: 'supermarket244-c0de3.firebasestorage.app',
    iosBundleId: 'com.example.localmartpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqs39GU6vJuestK-pxBmv3Rpz3AGzKo1M',
    appId: '1:193397693458:web:fb603e4d3e44023bbd8ccb',
    messagingSenderId: '193397693458',
    projectId: 'supermarket244-c0de3',
    authDomain: 'supermarket244-c0de3.firebaseapp.com',
    storageBucket: 'supermarket244-c0de3.firebasestorage.app',
    measurementId: 'G-XGRRJPD0VC',
  );
}
